version: "3.8"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=ubuntu
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5434:5432"
      - "5432:5432"
volumes:
  postgres:
    $ docker exec -it halver-v2_postgres_1 psql --dbname=halver --username=ubuntu --command="SHOW config_file"
